### PR TITLE
Handle DoubleSided materials

### PR DESCRIPTION
**Pull request by MadsHolten**
Related to [this PR on OBC](https://github.com/IFCjs/components/pull/5). Fix here first and create a new build that will be used in OBC.

### CODE REVIEW

**Comment by agviegas** [comment]
Hey, as double sided materials are more consuming that single-sided materials, I'm not sure if double-side should be the default 🤔 would a for loop to make all materials double sided be very inconvenient?

**Comment by MadsHolten** [comment]
On the other hand you know that the quality of IFCs can vary and I often find weird looking models because of this. I am currently handling it with a for loop.

**Comment by agviegas** [comment]
Hm, I see. Right now we are making huge fragment optimizations. Once we are done, maybe we can test both options (with and without) on various devices and see the results? If you want to be involved in that benchmark, let us know!

**Comment by MadsHolten** [comment]
Sure. Keep me posted :)

tor. 15. jun. 2023 11.31 skrev Antonio González Viegas <
***@***.***>:

**Comment by agviegas** [comment]
Closing this for now! I think that staying on the performance side by default is better, and a small loop is a small price to pay IMO  🙏🏻

**Pull request closed without merging**
